name: LangGraph Agent CI

on:
  push:
    branches: [ main, feat/IOOAG-01-langgraph ]
    paths:
      - '.github/workflows/ci.yml'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'README.md'
      - 'src/**'
      - 'Helm/**'
  pull_request:
    branches: [ main, feat/IOOAG-01-langgraph ]
    paths:
      - '.github/workflows/ci.yml'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'README.md'
      - 'src/**'
      - 'Helm/**'
  workflow_dispatch:

jobs:
  docker:
    uses: AGH-iot-agent/common-pipeline/.github/workflows/docker.yml@feat/IOTAG-01-common-pipeline
    with:
      image_repository: iot-agent-langgraph
      image_tag: ${{ github.sha }}
      docker_context: .
      dockerfile: Dockerfile
      image_output_dir: /mnt/storage/iot-agent/docker-local
      store_image_locally: true
      import_to_k3s: true

  deploy:
    needs: docker
    uses: AGH-iot-agent/common-pipeline/.github/workflows/helm.yml@feat/IOTAG-01-common-pipeline
    secrets: inherit
    with:
      service_name: iot-agent-langgraph
      release_name: iot-agent-langgraph
      namespace: ${{ github.event_name == 'pull_request' && 'iotag-sbx' || 'iotag-dev' }}
      chart_type: deployment
      values_file: ${{ github.event_name == 'pull_request' && 'Helm/values-sbx.yaml' || 'Helm/values-dev.yaml' }}
      image_repository: iot-agent-langgraph
      image_tag: ${{ github.sha }}
